on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Run PHP Lint
        run: "find src/ -name '*.php' | xargs -n1 php -l"

      - name: Install Composer dependencies
        run: "composer install --prefer-dist"

      - name: Run PHPUnit
        run: "vendor/bin/phpunit"
